### ISSUE TITLE
[JSON] winlibs-mingw-llvm-ucrt is not downloading

### ISSUE THREAD

**Issue by onurbbr** [chawyehsu/dorado#496]
![Untitled](https://user-images.githubusercontent.com/47495526/149833537-e62b3c44-f5be-451c-a837-38ac2a48e7fb.png)

**Comment by onurbbr** [comment]
Edit: Because the file name is too long, Windows 11 shortens the file name while downloading, so scoop can't find the file.

**Comment by chawyehsu** [comment]
Have you enabled the LongPaths support? You can run `scoop checkup` to see if it's enabled.

**Comment by onurbbr** [comment]
Obviously my scoop installation used the %localappdata% folder. Scoop is installed in "C:\Users\Onur\AppData\Local\Scoop".

**Comment by xiehao** [comment]
Same error, also appears when installing other similar packages, e.g. `mingw-winlibs` from `main` bucket.

**Comment by chawyehsu** [comment]
> Obviously my scoop installation used the %localappdata% folder. Scoop is installed in "C:\Users\Onur\AppData\Local\Scoop".

I don't know if it's your own choice of installing Scoop in `~/AppData/Local/scoop`. But this is a rather old issue about long path on Windows and Scoop changed its default root path from `~/AppData/Local/scoop` to `~/scoop` [years ago](https://github.com/ScoopInstaller/Scoop/blob/e5addb9487/lib/core.ps1#L1).

Scoop cannot download and save files when file path's length is exceeded. It's Windows's restriction. Either enable the  `LongPathsEnabled` support or change your cache directory (`scoop config cachePath 'C:\'` for example) to a different location to shorten the full path, so that Scoop can save downloaded files.
